<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\Command\ModifyProcessInstanceRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.ModifyProcessInstanceRequest.ActivateInstruction</code>
 */
class ActivateInstruction extends \Google\Protobuf\Internal\Message
{
    /**
     * the id of the element that should be activated
     *
     * Generated from protobuf field <code>string elementId = 1;</code>
     */
    protected $elementId = '';
    /**
     * the key of the ancestor scope the element instance should be created in;
     * set to -1 to create the new element instance within an existing element
     * instance of the flow scope
     *
     * Generated from protobuf field <code>int64 ancestorElementInstanceKey = 2;</code>
     */
    protected $ancestorElementInstanceKey = 0;
    /**
     * instructions describing which variables should be created
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ModifyProcessInstanceRequest.VariableInstruction variableInstructions = 3;</code>
     */
    private $variableInstructions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $elementId
     *           the id of the element that should be activated
     *     @type int|string $ancestorElementInstanceKey
     *           the key of the ancestor scope the element instance should be created in;
     *           set to -1 to create the new element instance within an existing element
     *           instance of the flow scope
     *     @type array<\ZeebeClient\Command\ModifyProcessInstanceRequest\VariableInstruction>|\Google\Protobuf\Internal\RepeatedField $variableInstructions
     *           instructions describing which variables should be created
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Command\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the id of the element that should be activated
     *
     * Generated from protobuf field <code>string elementId = 1;</code>
     * @return string
     */
    public function getElementId()
    {
        return $this->elementId;
    }

    /**
     * the id of the element that should be activated
     *
     * Generated from protobuf field <code>string elementId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setElementId($var)
    {
        GPBUtil::checkString($var, True);
        $this->elementId = $var;

        return $this;
    }

    /**
     * the key of the ancestor scope the element instance should be created in;
     * set to -1 to create the new element instance within an existing element
     * instance of the flow scope
     *
     * Generated from protobuf field <code>int64 ancestorElementInstanceKey = 2;</code>
     * @return int|string
     */
    public function getAncestorElementInstanceKey()
    {
        return $this->ancestorElementInstanceKey;
    }

    /**
     * the key of the ancestor scope the element instance should be created in;
     * set to -1 to create the new element instance within an existing element
     * instance of the flow scope
     *
     * Generated from protobuf field <code>int64 ancestorElementInstanceKey = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAncestorElementInstanceKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->ancestorElementInstanceKey = $var;

        return $this;
    }

    /**
     * instructions describing which variables should be created
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ModifyProcessInstanceRequest.VariableInstruction variableInstructions = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVariableInstructions()
    {
        return $this->variableInstructions;
    }

    /**
     * instructions describing which variables should be created
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ModifyProcessInstanceRequest.VariableInstruction variableInstructions = 3;</code>
     * @param array<\ZeebeClient\Command\ModifyProcessInstanceRequest\VariableInstruction>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVariableInstructions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ZeebeClient\Command\ModifyProcessInstanceRequest\VariableInstruction::class);
        $this->variableInstructions = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ActivateInstruction::class, \ZeebeClient\Command\ModifyProcessInstanceRequest_ActivateInstruction::class);

