<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\Command\ModifyProcessInstanceRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.ModifyProcessInstanceRequest.TerminateInstruction</code>
 */
class TerminateInstruction extends \Google\Protobuf\Internal\Message
{
    /**
     * the id of the element that should be terminated
     *
     * Generated from protobuf field <code>int64 elementInstanceKey = 1;</code>
     */
    protected $elementInstanceKey = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $elementInstanceKey
     *           the id of the element that should be terminated
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Command\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the id of the element that should be terminated
     *
     * Generated from protobuf field <code>int64 elementInstanceKey = 1;</code>
     * @return int|string
     */
    public function getElementInstanceKey()
    {
        return $this->elementInstanceKey;
    }

    /**
     * the id of the element that should be terminated
     *
     * Generated from protobuf field <code>int64 elementInstanceKey = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setElementInstanceKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->elementInstanceKey = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TerminateInstruction::class, \ZeebeClient\Command\ModifyProcessInstanceRequest_TerminateInstruction::class);

