<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace Camundity\PhpZeebe\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.DecisionRequirementsMetadata</code>
 */
class DecisionRequirementsMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * the dmn decision requirements ID, as parsed during deployment; together
     * with the versions forms a unique identifier for a specific decision
     *
     * Generated from protobuf field <code>string dmnDecisionRequirementsId = 1;</code>
     */
    protected $dmnDecisionRequirementsId = '';
    /**
     * the dmn name of the decision requirements, as parsed during deployment
     *
     * Generated from protobuf field <code>string dmnDecisionRequirementsName = 2;</code>
     */
    protected $dmnDecisionRequirementsName = '';
    /**
     * the assigned decision requirements version
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     */
    protected $version = 0;
    /**
     * the assigned decision requirements key, which acts as a unique identifier
     * for this decision requirements
     *
     * Generated from protobuf field <code>int64 decisionRequirementsKey = 4;</code>
     */
    protected $decisionRequirementsKey = 0;
    /**
     * the resource name (see: Resource.name) from which this decision
     * requirements was parsed
     *
     * Generated from protobuf field <code>string resourceName = 5;</code>
     */
    protected $resourceName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dmnDecisionRequirementsId
     *           the dmn decision requirements ID, as parsed during deployment; together
     *           with the versions forms a unique identifier for a specific decision
     *     @type string $dmnDecisionRequirementsName
     *           the dmn name of the decision requirements, as parsed during deployment
     *     @type int $version
     *           the assigned decision requirements version
     *     @type int|string $decisionRequirementsKey
     *           the assigned decision requirements key, which acts as a unique identifier
     *           for this decision requirements
     *     @type string $resourceName
     *           the resource name (see: Resource.name) from which this decision
     *           requirements was parsed
     * }
     */
    public function __construct($data = NULL) {
        \Camundity\PhpZeebe\Command\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the dmn decision requirements ID, as parsed during deployment; together
     * with the versions forms a unique identifier for a specific decision
     *
     * Generated from protobuf field <code>string dmnDecisionRequirementsId = 1;</code>
     * @return string
     */
    public function getDmnDecisionRequirementsId()
    {
        return $this->dmnDecisionRequirementsId;
    }

    /**
     * the dmn decision requirements ID, as parsed during deployment; together
     * with the versions forms a unique identifier for a specific decision
     *
     * Generated from protobuf field <code>string dmnDecisionRequirementsId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDmnDecisionRequirementsId($var)
    {
        GPBUtil::checkString($var, True);
        $this->dmnDecisionRequirementsId = $var;

        return $this;
    }

    /**
     * the dmn name of the decision requirements, as parsed during deployment
     *
     * Generated from protobuf field <code>string dmnDecisionRequirementsName = 2;</code>
     * @return string
     */
    public function getDmnDecisionRequirementsName()
    {
        return $this->dmnDecisionRequirementsName;
    }

    /**
     * the dmn name of the decision requirements, as parsed during deployment
     *
     * Generated from protobuf field <code>string dmnDecisionRequirementsName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDmnDecisionRequirementsName($var)
    {
        GPBUtil::checkString($var, True);
        $this->dmnDecisionRequirementsName = $var;

        return $this;
    }

    /**
     * the assigned decision requirements version
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * the assigned decision requirements version
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * the assigned decision requirements key, which acts as a unique identifier
     * for this decision requirements
     *
     * Generated from protobuf field <code>int64 decisionRequirementsKey = 4;</code>
     * @return int|string
     */
    public function getDecisionRequirementsKey()
    {
        return $this->decisionRequirementsKey;
    }

    /**
     * the assigned decision requirements key, which acts as a unique identifier
     * for this decision requirements
     *
     * Generated from protobuf field <code>int64 decisionRequirementsKey = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDecisionRequirementsKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->decisionRequirementsKey = $var;

        return $this;
    }

    /**
     * the resource name (see: Resource.name) from which this decision
     * requirements was parsed
     *
     * Generated from protobuf field <code>string resourceName = 5;</code>
     * @return string
     */
    public function getResourceName()
    {
        return $this->resourceName;
    }

    /**
     * the resource name (see: Resource.name) from which this decision
     * requirements was parsed
     *
     * Generated from protobuf field <code>string resourceName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setResourceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->resourceName = $var;

        return $this;
    }

}

