<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace Camundity\PhpZeebe\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.DecisionMetadata</code>
 */
class DecisionMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * the dmn decision ID, as parsed during deployment; together with the
     * versions forms a unique identifier for a specific decision
     *
     * Generated from protobuf field <code>string dmnDecisionId = 1;</code>
     */
    protected $dmnDecisionId = '';
    /**
     * the dmn name of the decision, as parsed during deployment
     *
     * Generated from protobuf field <code>string dmnDecisionName = 2;</code>
     */
    protected $dmnDecisionName = '';
    /**
     * the assigned decision version
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     */
    protected $version = 0;
    /**
     * the assigned decision key, which acts as a unique identifier for this
     * decision
     *
     * Generated from protobuf field <code>int64 decisionKey = 4;</code>
     */
    protected $decisionKey = 0;
    /**
     * the dmn ID of the decision requirements graph that this decision is part
     * of, as parsed during deployment
     *
     * Generated from protobuf field <code>string dmnDecisionRequirementsId = 5;</code>
     */
    protected $dmnDecisionRequirementsId = '';
    /**
     * the assigned key of the decision requirements graph that this decision is
     * part of
     *
     * Generated from protobuf field <code>int64 decisionRequirementsKey = 6;</code>
     */
    protected $decisionRequirementsKey = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dmnDecisionId
     *           the dmn decision ID, as parsed during deployment; together with the
     *           versions forms a unique identifier for a specific decision
     *     @type string $dmnDecisionName
     *           the dmn name of the decision, as parsed during deployment
     *     @type int $version
     *           the assigned decision version
     *     @type int|string $decisionKey
     *           the assigned decision key, which acts as a unique identifier for this
     *           decision
     *     @type string $dmnDecisionRequirementsId
     *           the dmn ID of the decision requirements graph that this decision is part
     *           of, as parsed during deployment
     *     @type int|string $decisionRequirementsKey
     *           the assigned key of the decision requirements graph that this decision is
     *           part of
     * }
     */
    public function __construct($data = NULL) {
        \Camundity\PhpZeebe\Command\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the dmn decision ID, as parsed during deployment; together with the
     * versions forms a unique identifier for a specific decision
     *
     * Generated from protobuf field <code>string dmnDecisionId = 1;</code>
     * @return string
     */
    public function getDmnDecisionId()
    {
        return $this->dmnDecisionId;
    }

    /**
     * the dmn decision ID, as parsed during deployment; together with the
     * versions forms a unique identifier for a specific decision
     *
     * Generated from protobuf field <code>string dmnDecisionId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDmnDecisionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->dmnDecisionId = $var;

        return $this;
    }

    /**
     * the dmn name of the decision, as parsed during deployment
     *
     * Generated from protobuf field <code>string dmnDecisionName = 2;</code>
     * @return string
     */
    public function getDmnDecisionName()
    {
        return $this->dmnDecisionName;
    }

    /**
     * the dmn name of the decision, as parsed during deployment
     *
     * Generated from protobuf field <code>string dmnDecisionName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDmnDecisionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->dmnDecisionName = $var;

        return $this;
    }

    /**
     * the assigned decision version
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * the assigned decision version
     *
     * Generated from protobuf field <code>int32 version = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * the assigned decision key, which acts as a unique identifier for this
     * decision
     *
     * Generated from protobuf field <code>int64 decisionKey = 4;</code>
     * @return int|string
     */
    public function getDecisionKey()
    {
        return $this->decisionKey;
    }

    /**
     * the assigned decision key, which acts as a unique identifier for this
     * decision
     *
     * Generated from protobuf field <code>int64 decisionKey = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDecisionKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->decisionKey = $var;

        return $this;
    }

    /**
     * the dmn ID of the decision requirements graph that this decision is part
     * of, as parsed during deployment
     *
     * Generated from protobuf field <code>string dmnDecisionRequirementsId = 5;</code>
     * @return string
     */
    public function getDmnDecisionRequirementsId()
    {
        return $this->dmnDecisionRequirementsId;
    }

    /**
     * the dmn ID of the decision requirements graph that this decision is part
     * of, as parsed during deployment
     *
     * Generated from protobuf field <code>string dmnDecisionRequirementsId = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDmnDecisionRequirementsId($var)
    {
        GPBUtil::checkString($var, True);
        $this->dmnDecisionRequirementsId = $var;

        return $this;
    }

    /**
     * the assigned key of the decision requirements graph that this decision is
     * part of
     *
     * Generated from protobuf field <code>int64 decisionRequirementsKey = 6;</code>
     * @return int|string
     */
    public function getDecisionRequirementsKey()
    {
        return $this->decisionRequirementsKey;
    }

    /**
     * the assigned key of the decision requirements graph that this decision is
     * part of
     *
     * Generated from protobuf field <code>int64 decisionRequirementsKey = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDecisionRequirementsKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->decisionRequirementsKey = $var;

        return $this;
    }

}

