<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace Camundity\PhpZeebe\Command;

if (false) {
    /**
     * This class is deprecated. Use Camundity\PhpZeebe\Command\Partition\PartitionBrokerHealth instead.
     * @deprecated
     */
    class Partition_PartitionBrokerHealth {}
}
class_exists(Partition\PartitionBrokerHealth::class);
@trigger_error('Camundity\PhpZeebe\Command\Partition_PartitionBrokerHealth is deprecated and will be removed in the next major release. Use Camundity\PhpZeebe\Command\Partition\PartitionBrokerHealth instead', E_USER_DEPRECATED);

