<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace Camundity\PhpZeebe\Command;

if (false) {
    /**
     * This class is deprecated. Use Camundity\PhpZeebe\Command\Partition\PartitionBrokerRole instead.
     * @deprecated
     */
    class Partition_PartitionBrokerRole {}
}
class_exists(Partition\PartitionBrokerRole::class);
@trigger_error('Camundity\PhpZeebe\Command\Partition_PartitionBrokerRole is deprecated and will be removed in the next major release. Use Camundity\PhpZeebe\Command\Partition\PartitionBrokerRole instead', E_USER_DEPRECATED);

