<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.DeployResourceResponse</code>
 */
class DeployResourceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * the unique key identifying the deployment
     *
     * Generated from protobuf field <code>int64 key = 1;</code>
     */
    protected $key = 0;
    /**
     * a list of deployed resources, e.g. processes
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.Deployment deployments = 2;</code>
     */
    private $deployments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $key
     *           the unique key identifying the deployment
     *     @type array<\ZeebeClient\Command\Deployment>|\Google\Protobuf\Internal\RepeatedField $deployments
     *           a list of deployed resources, e.g. processes
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Command\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the unique key identifying the deployment
     *
     * Generated from protobuf field <code>int64 key = 1;</code>
     * @return int|string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * the unique key identifying the deployment
     *
     * Generated from protobuf field <code>int64 key = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->key = $var;

        return $this;
    }

    /**
     * a list of deployed resources, e.g. processes
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.Deployment deployments = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeployments()
    {
        return $this->deployments;
    }

    /**
     * a list of deployed resources, e.g. processes
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.Deployment deployments = 2;</code>
     * @param array<\ZeebeClient\Command\Deployment>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeployments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ZeebeClient\Command\Deployment::class);
        $this->deployments = $arr;

        return $this;
    }

}

