<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\Command;

if (false) {
    /**
     * This class is deprecated. Use ZeebeClient\Command\ModifyProcessInstanceRequest\VariableInstruction instead.
     * @deprecated
     */
    class ModifyProcessInstanceRequest_VariableInstruction {}
}
class_exists(ModifyProcessInstanceRequest\VariableInstruction::class);
@trigger_error('ZeebeClient\Command\ModifyProcessInstanceRequest_VariableInstruction is deprecated and will be removed in the next major release. Use ZeebeClient\Command\ModifyProcessInstanceRequest\VariableInstruction instead', E_USER_DEPRECATED);

