<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.ModifyProcessInstanceRequest</code>
 */
class ModifyProcessInstanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * the key of the process instance that should be modified
     *
     * Generated from protobuf field <code>int64 processInstanceKey = 1;</code>
     */
    protected $processInstanceKey = 0;
    /**
     * instructions describing which elements should be activated in which scopes,
     * and which variables should be created
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ModifyProcessInstanceRequest.ActivateInstruction activateInstructions = 2;</code>
     */
    private $activateInstructions;
    /**
     * instructions describing which elements should be terminated
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ModifyProcessInstanceRequest.TerminateInstruction terminateInstructions = 3;</code>
     */
    private $terminateInstructions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $processInstanceKey
     *           the key of the process instance that should be modified
     *     @type array<\ZeebeClient\Command\ModifyProcessInstanceRequest\ActivateInstruction>|\Google\Protobuf\Internal\RepeatedField $activateInstructions
     *           instructions describing which elements should be activated in which scopes,
     *           and which variables should be created
     *     @type array<\ZeebeClient\Command\ModifyProcessInstanceRequest\TerminateInstruction>|\Google\Protobuf\Internal\RepeatedField $terminateInstructions
     *           instructions describing which elements should be terminated
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Command\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * the key of the process instance that should be modified
     *
     * Generated from protobuf field <code>int64 processInstanceKey = 1;</code>
     * @return int|string
     */
    public function getProcessInstanceKey()
    {
        return $this->processInstanceKey;
    }

    /**
     * the key of the process instance that should be modified
     *
     * Generated from protobuf field <code>int64 processInstanceKey = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProcessInstanceKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->processInstanceKey = $var;

        return $this;
    }

    /**
     * instructions describing which elements should be activated in which scopes,
     * and which variables should be created
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ModifyProcessInstanceRequest.ActivateInstruction activateInstructions = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActivateInstructions()
    {
        return $this->activateInstructions;
    }

    /**
     * instructions describing which elements should be activated in which scopes,
     * and which variables should be created
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ModifyProcessInstanceRequest.ActivateInstruction activateInstructions = 2;</code>
     * @param array<\ZeebeClient\Command\ModifyProcessInstanceRequest\ActivateInstruction>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActivateInstructions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ZeebeClient\Command\ModifyProcessInstanceRequest\ActivateInstruction::class);
        $this->activateInstructions = $arr;

        return $this;
    }

    /**
     * instructions describing which elements should be terminated
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ModifyProcessInstanceRequest.TerminateInstruction terminateInstructions = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTerminateInstructions()
    {
        return $this->terminateInstructions;
    }

    /**
     * instructions describing which elements should be terminated
     *
     * Generated from protobuf field <code>repeated .gateway_protocol.ModifyProcessInstanceRequest.TerminateInstruction terminateInstructions = 3;</code>
     * @param array<\ZeebeClient\Command\ModifyProcessInstanceRequest\TerminateInstruction>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTerminateInstructions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ZeebeClient\Command\ModifyProcessInstanceRequest\TerminateInstruction::class);
        $this->terminateInstructions = $arr;

        return $this;
    }

}

