<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\Command;

if (false) {
    /**
     * This class is deprecated. Use ZeebeClient\Command\ModifyProcessInstanceRequest\ActivateInstruction instead.
     * @deprecated
     */
    class ModifyProcessInstanceRequest_ActivateInstruction {}
}
class_exists(ModifyProcessInstanceRequest\ActivateInstruction::class);
@trigger_error('ZeebeClient\Command\ModifyProcessInstanceRequest_ActivateInstruction is deprecated and will be removed in the next major release. Use ZeebeClient\Command\ModifyProcessInstanceRequest\ActivateInstruction instead', E_USER_DEPRECATED);

