<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\Command;

if (false) {
    /**
     * This class is deprecated. Use ZeebeClient\Command\ModifyProcessInstanceRequest\TerminateInstruction instead.
     * @deprecated
     */
    class ModifyProcessInstanceRequest_TerminateInstruction {}
}
class_exists(ModifyProcessInstanceRequest\TerminateInstruction::class);
@trigger_error('ZeebeClient\Command\ModifyProcessInstanceRequest_TerminateInstruction is deprecated and will be removed in the next major release. Use ZeebeClient\Command\ModifyProcessInstanceRequest\TerminateInstruction instead', E_USER_DEPRECATED);

