<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\Command;

if (false) {
    /**
     * This class is deprecated. Use ZeebeClient\Command\Partition\PartitionBrokerRole instead.
     * @deprecated
     */
    class Partition_PartitionBrokerRole {}
}
class_exists(Partition\PartitionBrokerRole::class);
@trigger_error('ZeebeClient\Command\Partition_PartitionBrokerRole is deprecated and will be removed in the next major release. Use ZeebeClient\Command\Partition\PartitionBrokerRole instead', E_USER_DEPRECATED);

