<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeebe.proto

namespace ZeebeClient\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway_protocol.ProcessInstanceCreationStartInstruction</code>
 */
class ProcessInstanceCreationStartInstruction extends \Google\Protobuf\Internal\Message
{
    /**
     * element ID
     *
     * Generated from protobuf field <code>string elementId = 1;</code>
     */
    protected $elementId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $elementId
     *           element ID
     * }
     */
    public function __construct($data = NULL) {
        \ZeebeClient\Command\Zeebe::initOnce();
        parent::__construct($data);
    }

    /**
     * element ID
     *
     * Generated from protobuf field <code>string elementId = 1;</code>
     * @return string
     */
    public function getElementId()
    {
        return $this->elementId;
    }

    /**
     * element ID
     *
     * Generated from protobuf field <code>string elementId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setElementId($var)
    {
        GPBUtil::checkString($var, True);
        $this->elementId = $var;

        return $this;
    }

}

